model:
  name: fcn_resnet50
  weights: COCO_WITH_VOC_LABELS_V1
  weights_backbone: None
  aux_loss: true
  num_classes: 2

train:
  dataset_root: ./dataset
  result_dir: ./results/train

  resume: false

  batch_size: 2
  num_workers: 0

  n_epochs: 10
  lr: 0.01
  momentum: 0.9
  weight_decay: 0.0001

  save_freq: 1

eval:
  checkpoint:  ./results/train/model_best.pth

  dataset_path: ./dataset/test
  result_dir: ./results/eval

  figsize: [15, 10]
  probability_threshold: 0.5  
  alpha: 0.8                  
  color: [0, 0, 0]           
