model:
  name: fcn_resnet50
  weights: None
  weights_backbone: None
  aux_loss: true
  num_classes: 2

predict:
  checkpoint: ./results/train/model_best.pth

  dataset_path: ./dataset/test/images
  result_dir: ./results/predict

  figsize: [10, 10]
  probability_threshold: 0.5  
  alpha: 0.8                 
  color: [0, 0, 0]            